name: Update RSS Feed

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  update_feed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run script
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: python script.py
    
    - name: Generate index.html
      run: python make_index.py
    
    - name: Copy files to gh-pages branch
      run: |
        cp rss.xml gh-pages/
        cp index.html gh-pages/
    
    - name: Commit and push changes
      run: |
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rss.xml
        git add index.html
        git commit -m "Update RSS feed" || echo "No changes to commit"
        git push origin HEAD:gh-pages --force